version: '3'
services:
  node:
    image: node:14
    build: .
    command: yarn start
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    external_links:
      - mongo
    env_file: .env
  mongo:
    image: mongo:4.4.6
    command: [--auth]
    ports:
      - '27017:27017'
    volumes:
      - ./__data__:/data/db